export class BomSheetDataModel{
    id:number;
    bomId:number;
    bomItemId:number;
    bomNo:string;
    itemName:string;
    itemTypeName:string;
    categoryName:string;
    description:string;
    gmtColor:string;
    colorCode:string;
    itemColor:string;
    itemColorCode:string;
    colorWiseItemCode:string;
    gmtSize:string;
    itemSize:string;
    itemSizeUnit:string;
    itemSizeWithUnit:string;
    refCode:string;
    supplierId:number;
    supplierName:string;
    consumption:number;
    uomId:number;
    uomName:string;
    effectedQty:number;
    requiredQty:number;
    wastagePercentage:number;
    additionalQty:number;
    totalQty:number;
    rate:number;
    totalAmount:number;
    remarks:string;
    category:string;
    categoryId:number;
    bookQty:number;
    bookedQty:number;
    balance:number;
    materialId:number;
    fileComment:string;
    activeStatus:string;
    fileId:number;
    salesContractId :number;
    salesContractNo : string;
    salesContract : string;
    component:string;
    poNo:string;
    actualDescription:string;
    color:string;
    gmtQty :number;
    originalQty :number;
    wastageQty :number;
    balanceFlag:string;
    costCategoryGroup:string;
    stylePart:string;
    stylePartString:string;
    stylePartId:number;
    styleId:number;
    styleName:string;
    styleSalesContractId :number;
    styleSalesContractNo : string;
    buyingTeamComment : string;
    bigConsumption:number
    tall1Consumption:number;
    regularConsumption:number;
    shortConsumption:number
    tall2Consumption:number;
    averageConsumption:number;
    bigQty:number
    tall1Qty:number;
    regularQty:number;
    shortQty:number
    tall2Qty:number;
    averageQty:number;
    sizeSubGroup:string;
    sizeMainGroup:string;
    colorStatus:string;
    threadBrandId: number;
    threadBrandName: string;
    threadTexId: number;
    threadTexName: string;
    threadTicketId: number;
    threadTicketNo: string
    threadConversionValue: number;
    threadArticle: string;
    mkuId:number;
    mkuName:string;
    marketRelation:string;
    itemPlacement:string;
    sfc:string;
    dsmCode:string;
    criticalItemFact:number;
    criticalItemFactString:string;
    threadShade:string;
    threadFinish:string;
    isUsedStock: boolean;
    IsUsedStockColoumShow: boolean;
    bookingStockQty:number;
    bomStockQty:number;
    buyDate:string;
    sizeCode:string;
    descriptionShowMore: boolean;
    descriptionShowMoreLessOption: boolean;
    actualDescriptionShowMore: boolean;
    actualDescriptionShowMoreLessOption: boolean;
    itemPlacementShowMore: boolean;
    itemPlacementShowMoreLessOption: boolean;
}