export class BomMaterialConsumptionModel{
    id : number;
    bomId : number;
    bomNo : string;
    categoryId : number;
    categoryName : string;
    itemId : number;
    itemName : string;
    itemType : string;
    itemTypeName : string;
    usedPlace : string;
    refCode : string;
    nominationStatus : string;
    nominationName:string;
    supplierId : number;
    supplierName : string;
    consumption : number;
    measurementUnitId : number;
    measurementUnit : string;
    wastagePercentage : number;
    totalConsumption :number;
    rate : number;
    currencyId : number;
    currency : string;
    currencyConversion : number;
    finCostPc : number;
    isfincostpcName : String;
    isfincostpc : number;
    value : number;
    itemCode : string;
    countryId : number;
    countryName : string;
    cuttAbleWidth : number;
    itemPlacement : string;
    mkuId : number;
    mkuName : string;
    marketRelation :number;
    priceMoodId : number;
    priceMood : string;
    costFact : number;
    description : string;
    actualDescription : string;
    uomId : number;
    uomName : string;
    bomComment : string;
    sizeFact : number;
    colorFact : number;
    criticalItemFact : number;
    poFact : number;
    sizeCheckStatus:boolean;
    poCheckStatus:boolean;
    colorCheckStatus:boolean;
    criticalItemCheckStatus:boolean;
    costingId: number;
    quotationNumber:string;
    styleId:number;
    styleName:string;
    bookStatus:boolean;
    bookingStatus:number;
    stylePartId:number;
    bomItemId:number;
    buyerId:number;
    stylePart:string;
    callFrom:string;
    stylePartString:string;
    buyingTeamComment:string;
    bigConsumption:number;
    regularConsumption:number;
    tall1Consumption:number;
    isColorBomSetup:number;
    isSizeBomSetup:number;
    sizeGroup: string;
    consumptionGroup: string;

    tall2Consumption:number;
    averageConsumption:number;
    shortConsumption:number;
    isNewRow: number;
    dsmCode: string;
    costCategoryGroup: string;
    descriptionShowMore: boolean;
    descriptionShowMoreLessOption: boolean;
    actualDescriptionShowMore: boolean;
    actualDescriptionShowMoreLessOption: boolean;
    itemPlacementShowMore: boolean;
    itemPlacementShowMoreLessOption: boolean;
}