export class DataForTrackingDasboarModel {
  buyerId: number;
  buyerName: string;
  seasonId: number;
  seasonName: string;
  yearId: number;
  seasonYear: string;
  styleId: number;
  styleName: string;
  brandId: number;
  brandName: string;
  fgModel: string;
  gmtItemId: number;
  productCategory: string;
  poNo: string;
  bookingPo: string;
  poQty: number;
  forecastQty: number;
  bookingInsQty: number;
  buyDate: string;
  categoryId: number;
  category: string;
  dsmCode: string;
  itemDescription: string;
  itemCode: string;
  color: string;
  consumption: number;
  wastagePercentage: number;
  bookingConsumption: number;
  unit: string;
  gmtSize: string;
  measurement: string;
  sizeWiseQty: number;
  rate: number;
  requiredQty: number;
  bookQty: number;
  bookingUnit: string;
  totalShipQty: number;
  balanceQty: number;
  approxInhouseDate: string | null;
  bookDate: string | null;
  etaDate: string | null;
  etdDate: string | null;
  inhouseDate: string | null;
  orderReceiveDate: string;
  fgShipDate: string;
  lineStartDate: string | null;
  userArea: string;
  specialComments: string;
  incoterm: string;
  supplierName: string;
  sampleApprovalDateStatus: string;
  bookingConcern: string;
  checkingConcern: string;
  programCategory: string;
  piNo: string;
  piQuantity: number;
  paymentTerm: string;
  lcNo: string;
  lcContractNo: string;
  lcGivenDate: string;
  status: string;
  lotNumber: string;
}