export class FabricDetailModel {
    id:number;
    categoryId:number;
    fabricCategoryId:number;
    categoryName:string;
    placement:string;
    itemPlacement:string;
    description:string;
    instruction:string;
    itemId:number;
    refCode:string;
    itemName:string;
    itemGroup: string;
    //fileType:string;
    ordSl: number;
    stylePartId:number;
    partId:number;
    partName:string;
    remarks:string;
    stylePartSetupId:number;
    styleSettingId:number;
    colorName: string;
    itemCode: string;    
    uomName: string;
    uomId: number;
    buyerConsumption: number;
    consumption: number;
    quantity: number;
    checkMarkingInformation: string;
    sourceOfMaterial: string;
    unit: string;
    sizeName: string;
    stockType: string;
    mesurementUnitId: number;
    gmtItemId: number;
    gmtSubTypeId: number;
    sampleColor: string;
    categoryGroup:string;
    isArtwork: boolean;
    isWashRecipe: boolean;
    isDataSheet:boolean;
    isDensity:boolean;
    costCategoryGroup: string;
    colorFact: number;
    sizeFact: number;
    gmtColor: string;
    gmtSize: string;
    itemColorCode: string;
    itemSize: string;
    dsmCode: string;
    cuttableWidth: number;
    fabricWidth: number;
    itemColor: string;
    modelCode: string;
}
